CREATE TABLE [dbo].[articleOld] (
    [idN]           INT            NOT NULL,
    [Producer]      NVARCHAR (255) NULL,
    [LabelName]     NVARCHAR (255) NULL,
    [Country]       NVARCHAR (255) NULL,
    [Region]        NVARCHAR (255) NULL,
    [Location]      NVARCHAR (255) NULL,
    [Locale]        NVARCHAR (255) NULL,
    [Site]          NVARCHAR (255) NULL,
    [Vintage]       NVARCHAR (255) NULL,
    [Variety]       NVARCHAR (255) NULL,
    [ColorClass]    NVARCHAR (255) NULL,
    [Title]         NVARCHAR (255) NULL,
    [Topic]         NVARCHAR (255) NULL,
    [Publication]   NVARCHAR (255) NULL,
    [Source]        NVARCHAR (255) NULL,
    [sourceDate]    SMALLDATETIME  NULL,
    [Issue]         NVARCHAR (255) NULL,
    [Pages]         NVARCHAR (255) NULL,
    [ArticleId]     INT            NULL,
    [sourceFile]    NVARCHAR (255) NULL,
    [Notes]         NTEXT          NULL,
    [NotesLen]      INT            NULL,
    [offsetInFile]  INT            NULL,
    [isArticle]     BIT            NOT NULL,
    [inFreeArea]    BIT            NOT NULL,
    [Temp]          NTEXT          NULL,
    [whoUpdated]    NVARCHAR (255) NULL,
    [dateUpdated]   SMALLDATETIME  NULL,
    [WineSummary]   NVARCHAR (255) NULL,
    [ArticleIdNKey] INT            NULL,
    [EntryType]     NVARCHAR (255) NULL,
    [createDate]    SMALLDATETIME  CONSTRAINT [df_articleOld_createDate] DEFAULT (getdate()) NULL
);

