CREATE TABLE [dbo].[Articles] (
    [idN]           INT            NOT NULL,
    [Producer]      NVARCHAR (MAX) NULL,
    [LabelName]     NVARCHAR (MAX) NULL,
    [Country]       NVARCHAR (MAX) NULL,
    [Region]        NVARCHAR (MAX) NULL,
    [Location]      NVARCHAR (MAX) NULL,
    [Locale]        NVARCHAR (MAX) NULL,
    [Site]          NVARCHAR (MAX) NULL,
    [Vintage]       NVARCHAR (MAX) NULL,
    [Variety]       NVARCHAR (MAX) NULL,
    [ColorClass]    NVARCHAR (MAX) NULL,
    [Title]         NVARCHAR (MAX) NULL,
    [Topic]         NVARCHAR (MAX) NULL,
    [Publication]   NVARCHAR (MAX) NULL,
    [Source]        NVARCHAR (MAX) NULL,
    [sourceDate]    DATETIME       NULL,
    [Issue]         NVARCHAR (MAX) NULL,
    [Pages]         NVARCHAR (MAX) NULL,
    [ArticleId]     INT            NULL,
    [sourceFile]    NVARCHAR (MAX) NULL,
    [Notes]         NVARCHAR (MAX) NULL,
    [NotesLen]      INT            NULL,
    [offsetInFile]  INT            NULL,
    [isArticle]     SMALLINT       NOT NULL,
    [inFreeArea]    SMALLINT       NOT NULL,
    [Temp]          NVARCHAR (MAX) NULL,
    [whoUpdated]    NVARCHAR (MAX) NULL,
    [dateUpdated]   DATETIME       NULL,
    [WineSummary]   NVARCHAR (MAX) NULL,
    [ArticleIdNKey] INT            NULL,
    [EntryType]     NVARCHAR (MAX) NULL
);

