CREATE TABLE [dbo].[tastingNew] (
    [tastingN]                   INT             IDENTITY (1, 1) NOT NULL,
    [wineN]                      INT             NOT NULL,
    [vinN]                       INT             NULL,
    [wineNameN]                  INT             NULL,
    [pubN]                       INT             NULL,
    [pubDate]                    SMALLDATETIME   NULL,
    [issue]                      VARCHAR (50)    NULL,
    [pages]                      VARCHAR (50)    NULL,
    [articleId]                  SMALLINT        NULL,
    [_x_articleIdNKey]           INT             NULL,
    [articleOrder]               SMALLINT        NULL,
    [articleURL]                 VARCHAR (500)   NULL,
    [notes]                      VARCHAR (MAX)   NULL,
    [tasterN]                    INT             NULL,
    [tasteDate]                  SMALLDATETIME   NULL,
    [isMostRecentTasting]        BIT             NULL,
    [isNoTasting]                BIT             NULL,
    [isActiveForThisPub]         BIT             NULL,
    [_x_IsActiveWineN]           BIT             NULL,
    [isBorrowedDrinkDate]        BIT             NULL,
    [IsBarrelTasting]            BIT             NULL,
    [bottleSizeN]                SMALLINT        NULL,
    [rating]                     TINYINT         NULL,
    [ratingPlus]                 BIT             NULL,
    [ratingHi]                   TINYINT         NULL,
    [ratingShow]                 VARCHAR (50)    NULL,
    [drinkDate]                  DATETIME        NULL,
    [drinkDateHi]                DATETIME        NULL,
    [drinkWhenN]                 SMALLINT        NULL,
    [maturityN]                  SMALLINT        NULL,
    [estimatedCostLo]            MONEY           NULL,
    [estimatedCostHi]            MONEY           NULL,
    [originalCurrencyN]          SMALLINT        NULL,
    [provenanceN]                SMALLINT        NULL,
    [whereTastedN]               SMALLINT        NULL,
    [isAvailabeToTastersGroups]  BIT             NULL,
    [isPostedToBB]               BIT             NULL,
    [isAnnonymous]               BIT             NULL,
    [isPrivate]                  BIT             NULL,
    [updateWhN]                  INT             NULL,
    [_clumpName]                 VARCHAR (500)   NULL,
    [_fixedId]                   INT             NULL,
    [_x_hasAGalloniTasting]      BIT             NULL,
    [_x_HasCurrentPrice]         BIT             NULL,
    [_x_hasDSchildknechtTasting] BIT             NULL,
    [_x_hasDThomasesTasting]     BIT             NULL,
    [_x_hasErpTasting]           BIT             NULL,
    [_x_hasJMillerTasting]       BIT             NULL,
    [_x_hasMSquiresTasting]      BIT             NULL,
    [_x_hasMultipleWATastings]   BIT             NULL,
    [_x_hasNMartinTasting]       BIT             NULL,
    [_x_hasProducerProfile]      BIT             NULL,
    [_x_HasProducerWebSite]      BIT             NULL,
    [_x_hasPRovaniTasting]       BIT             NULL,
    [_x_hasRParkerTasting]       BIT             NULL,
    [_x_hasWJtasting]            BIT             NULL,
    [_x_reviewerIdN]             INT             NULL,
    [ratingQ]                    NVARCHAR (MAX)  NULL,
    [createDate]                 SMALLDATETIME   NULL,
    [createWh]                   INT             NULL,
    [rowversion]                 ROWVERSION      NOT NULL,
    [isInactive]                 BIT             NULL,
    [articleMasterN]             INT             NULL,
    [decantedN]                  SMALLINT        NULL,
    [isApproved]                 BIT             NULL,
    [hasUserComplaint]           BIT             NULL,
    [updateDate]                 SMALLDATETIME   NULL,
    [hasHad]                     NCHAR (10)      NULL,
    [userComplaintCount]         SMALLINT        NULL,
    [hasRating]                  BIT             NULL,
    [isErpTasting]               BIT             NULL,
    [ParkerZralyLevel]           TINYINT         NULL,
    [sourceIconN]                TINYINT         NULL,
    [isProTasting]               BIT             NULL,
    [canBeActiveTasting]         BIT             NULL,
    [_x_showForERP]              BIT             NULL,
    [_x_showForWJ]               BIT             NULL,
    [_fixedIdDeleted]            BIT             NULL,
    [dataIdN]                    INT             NULL,
    [dataIdNDeleted]             INT             NULL,
    [dataSourceN]                INT             NULL,
    [hasRating2]                 AS              (case when [rating]>(0) then (1) else (0) end) PERSISTED NOT NULL,
    [joinX]                      NVARCHAR (1000) NULL
);


GO
CREATE NONCLUSTERED INDEX [ix_tastingNew_fixedId]
    ON [dbo].[tastingNew]([_fixedId] ASC);

