


CREATE VIEW [dbo].[vWine4Erp]

AS 

select [IsActiveWineN]
      ,[WineN] = isnull(oldWineN, 250000 + WineN)
      ,[Vintage]
      ,[Variety]
      ,[LabelName]
      ,[Producer]
      ,[ProducerShow]
      ,[RatingShow]
      ,[Country]
      ,[Region]
      ,[Location]
      ,[Dryness]
      ,[ColorClass]
      ,[WineType]
      ,[Source]
      ,[SourceDate]
      ,[Publication]
      ,[Issue]
      ,[Pages]
      ,[Rating]
      ,[Rating_Hi]
      ,[ratingQ]
      ,[DrinkDate]
      ,[DrinkDate_Hi]
      ,[EstimatedCost]
      ,[EstimatedCost_Hi]
      ,[BottlesPerCosting]
      ,[BottleSize]
      ,[Notes]
      ,[IsActiveTasting]
      ,[TastingCount]
      ,[DateUpdated]
      ,[WhoUpdated]
      ,[encodedKeyWords]
      ,[Vin] 
      ,[VinN]		-- = isnull(oldVinN, 250000 + VinN)
      ,[ThisYearHasPrices]
      ,[SomeYearHasPrices]
      ,[Locale]
      ,[HasProducerWebSite]
      ,[Site]
      ,[IsBarrelTasting]
      ,[ArticleIdNKey]
      ,[ArticleId]
      ,[ArticleOrder]
      ,[CombinedLocation]
      ,[Maturity]
      ,[ProducerURL]
      ,[Places]
      ,[ShortLabelName]
      ,[HasCurrentPrice]
      ,[DisabledFlag]
      ,[NameCreatorWhoN]
      ,[UserCount]
      ,[HasERPTasting] = case 
			when hasErpTasting is null then isnull(isActiveWineN, 0)
			else hasErpTasting
		end
      ,[RecordCreatorWhoN]
      ,[RecordCreatedDate]
      ,[IsERPName]
      ,[MostRecentPrice]
      ,[MostRecentPriceHi]
      ,[MostRecentPriceCnt]
      ,[mostRecentAuctionPrice]
      ,[mostRecentAuctionPriceHi]
      ,[mostRecentAuctionPriceCnt]
      ,[HasUserNotes]
      ,[Wid]
      ,[IsCurrentlyForSale]
      ,[isCurrentlyOnAuction]
      ,[ReviewerIdN]
      ,[IdN]
      ,[HasWJTasting] = isnull(HasWJTasting, 0)
      ,[showForERP]
      ,[showForWJ]
      ,[hasAGalloniTasting]
      ,[hasDSchildknechtTasting]
      ,[hasDThomasesTasting]
      ,[hasJMillerTasting]
      ,[hasMSquiresTasting]
      ,[hasNMartinTasting]
      ,[hasPRovaniTasting]
      ,[hasRParkerTasting]
      ,[FixedId]
      ,[shortTitle]
      ,[isErpLocationOK]
      ,[isErpProducerOK]
      ,[isProducerTranslated]
      ,[isErpRegionOK]
      ,[isErpVarietyOK]
      ,[isVinnDeduced]
      ,[isWineNDeduced]
      ,[wineNameIdN]
      ,[hasProducerProfile]
      ,[clumpName]
      ,[isBorrowedDrinkDate]
      ,[hasMultipleWATastings]
      ,[ProducerProfileFileName]
      ,[isErpTasting]
      ,[isWjTasting]
      ,[mostRecentPriceAvg]
      ,[qprAllShow]
      ,[qprAllShowI]
      ,[qprRaw]
      ,[qprGroup]
      ,[qprGroupRankShow]
      ,[qprGroupRankShowI]
      ,[qprGroupShow]
      ,[qprGroupShowI]
      ,[erpTastingCount]
      ,[isActiveWineN_old]
      ,[joinx]
      ,[wineNameN]
from Wine