CREATE TABLE [dbo].[JRulesWine] (
    [EntryN]             INT            NULL,
    [IsActiveWineN]      BIT            NOT NULL,
    [WineN]              INT            NULL,
    [Vintage]            NVARCHAR (255) NULL,
    [Variety]            NVARCHAR (255) NULL,
    [LabelName]          NVARCHAR (255) NULL,
    [Producer]           NVARCHAR (255) NULL,
    [Country]            NVARCHAR (255) NULL,
    [Region]             NVARCHAR (255) NULL,
    [Location]           NVARCHAR (255) NULL,
    [Dryness]            NVARCHAR (255) NULL,
    [ColorClass]         NVARCHAR (255) NULL,
    [WineType]           NVARCHAR (255) NULL,
    [Source]             NVARCHAR (255) NULL,
    [SourceDate]         DATETIME       NULL,
    [Publication]        NVARCHAR (50)  NULL,
    [Issue]              NVARCHAR (50)  NULL,
    [Pages]              NVARCHAR (50)  NULL,
    [Rating]             SMALLINT       NULL,
    [Rating_Hi]          SMALLINT       NULL,
    [RatingQ]            NVARCHAR (MAX) NULL,
    [DrinkDate]          DATETIME       NULL,
    [DrinkDate_Hi]       DATETIME       NULL,
    [EstimatedCost]      MONEY          NULL,
    [EstimatedCost_Hi]   MONEY          NULL,
    [BottlesPerCosting]  SMALLINT       NULL,
    [BottleSize]         NVARCHAR (50)  NULL,
    [Notes]              NVARCHAR (MAX) NULL,
    [IsActiveTasting]    SMALLINT       NULL,
    [TastingCount]       SMALLINT       NULL,
    [DateUpdated]        DATETIME       NULL,
    [WhoUpdated]         NVARCHAR (50)  NULL,
    [FixedId]            INT            NOT NULL,
    [encodedKeyWords]    NVARCHAR (255) NULL,
    [Vin]                NVARCHAR (255) NULL,
    [VinN]               INT            NULL,
    [ThisYearHasPrices]  BIT            NOT NULL,
    [SomeYearHasPrices]  BIT            NOT NULL,
    [Locale]             NVARCHAR (255) NULL,
    [HasProducerWebSite] BIT            NOT NULL,
    [Site]               NVARCHAR (255) NULL,
    [IsBarrelTasting]    BIT            NOT NULL,
    [ArticleIdNKey]      INT            NULL,
    [ArticleId]          INT            NULL,
    [ArticleOrder]       INT            NULL,
    [shortLabelName]     NVARCHAR (MAX) NULL,
    [clumpName]          NVARCHAR (50)  NULL,
    [borrowedDrinkDate]  BIT            NOT NULL
);

