CREATE TABLE [dbo].[julianRulesTest202] (
    [xWineN]        INT            NULL,
    [wineN]         INT            NULL,
    [vinn]          INT            NULL,
    [xvintage]      NVARCHAR (255) NULL,
    [Vintage]       NVARCHAR (255) NULL,
    [XProducerShow] NVARCHAR (MAX) NULL,
    [ProducerShow]  NVARCHAR (MAX) NULL,
    [producer]      NVARCHAR (255) NULL,
    [Xlabelname]    NVARCHAR (255) NULL,
    [LabelName]     NVARCHAR (255) NULL,
    [Xvariety]      NVARCHAR (255) NULL,
    [variety]       NVARCHAR (255) NULL,
    [XcolorClass]   NVARCHAR (255) NULL,
    [colorClass]    NVARCHAR (255) NULL,
    [Xwinetype]     NVARCHAR (255) NULL,
    [winetype]      NVARCHAR (255) NULL,
    [Xdryness]      NVARCHAR (255) NULL,
    [dryness]       NVARCHAR (255) NULL,
    [Xcountry]      NVARCHAR (255) NULL,
    [Country]       NVARCHAR (255) NULL,
    [Xregion]       NVARCHAR (255) NULL,
    [Region]        NVARCHAR (255) NULL,
    [Xlocation]     NVARCHAR (255) NULL,
    [location]      NVARCHAR (255) NULL,
    [Xlocale]       NVARCHAR (255) NULL,
    [Locale]        NVARCHAR (255) NULL,
    [Xsite]         NVARCHAR (255) NULL,
    [Site]          NVARCHAR (255) NULL
);

