CREATE TABLE [dbo].[userWinesTemplate] (
    [id]                     INT            IDENTITY (1, 1) NOT NULL,
    [Vintage]                VARCHAR (MAX)  NULL,
    [MyWineName]             VARCHAR (MAX)  NULL,
    [Supplier]               VARCHAR (MAX)  NULL,
    [PurchaseQuantity]       VARCHAR (MAX)  NULL,
    [BottleSize]             VARCHAR (MAX)  NULL,
    [PurchaseDate]           VARCHAR (MAX)  NULL,
    [DeliveryDate]           VARCHAR (MAX)  NULL,
    [Price]                  VARCHAR (MAX)  NULL,
    [Location]               VARCHAR (MAX)  NULL,
    [erpWineName]            VARCHAR (MAX)  NULL,
    [wineN]                  INT            NULL,
    [myVintage]              NCHAR (10)     NULL,
    [noMatch]                BIT            NULL,
    [rowFlag]                SMALLINT       NULL,
    [errors]                 VARCHAR (MAX)  NULL,
    [hasErpTasting]          BIT            NULL,
    [presentBeforeThisCycle] BIT            NULL,
    [twoErpMatches]          BIT            NULL,
    [setByUser]              BIT            NULL,
    [fromSameVintage]        BIT            NULL,
    [fromOtherVintage]       BIT            NULL,
    [comments]               NVARCHAR (MAX) NULL,
    [newVintageOK]           BIT            NULL,
    [matchIsTentative]       BIT            NULL,
    [Alert]                  NVARCHAR (MAX) NULL,
    [isDetail]               BIT            NULL
);

