CREATE TABLE [dbo].[whex] (
    [whN]                                           INT            IDENTITY (1, 1) NOT NULL,
    [memberCnt]                                     INT            NULL,
    [myQualifications]                              NVARCHAR (200) NULL,
    [recentSpanMonths]                              INT            NULL,
    [needToDrinkSpanMonths]                         INT            NULL,
    [whoTrustsMeCnt]                                INT            NULL,
    [forSaleWineCnt]                                INT            NULL,
    [forSaleBuyerCnt]                               INT            NULL,
    [wantToBuyWineCnt]                              INT            NULL,
    [wantToBuySellerCnt]                            INT            NULL,
    [watchListCnt]                                  INT            NULL,
    [needToDrinkWineCnt]                            INT            NULL,
    [needToDrinkBottleCnt]                          INT            NULL,
    [trustedTasterTastingNoteCnt]                   INT            NULL,
    [trustedTasterTastingNoteRecentCnt]             INT            NULL,
    [trustedTasterTastingNoteRatedHelpfulCnt]       INT            NULL,
    [trustedTasterTastingNoteRatedHelpfulRecentCnt] INT            NULL,
    [trustedTasterTastingNoteViewCnt]               INT            NULL,
    [trustedTasterTastingNoteViewRecentCnt]         INT            NULL,
    [trustedTasterArticleCnt]                       INT            NULL,
    [trustedTasterArticleRecentCnt]                 INT            NULL,
    [trustedTasterArticleRatedHelpfulCnt]           INT            NULL,
    [trustedTasterArticleRatedHelpfulRecentCnt]     INT            NULL,
    [trustedTasterArticleViewCnt]                   INT            NULL,
    [trustedTasterArticleViewRecentCnt]             INT            NULL,
    [myPublicationTastingNoteCnt]                   INT            NULL,
    [myPublicationTastingNoteRecentCnt]             INT            NULL,
    [myPublicationTastingNoteRatedHelpfulCnt]       INT            NULL,
    [myPublicationTastingNoteRatedHelpfulRecentCnt] INT            NULL,
    [myPublicationTastingNoteViewCnt]               INT            NULL,
    [myPublicationTastingNoteViewRecentCnt]         INT            NULL,
    [myPublicationArticleCnt]                       INT            NULL,
    [myPublicationArticleRecentCnt]                 INT            NULL,
    [myPublicationArticleRatedHelpfulCnt]           INT            NULL,
    [myPublicationArticleRatedHelpfulRecentCnt]     INT            NULL,
    [myPublicationArticleViewCnt]                   INT            NULL,
    [myPublicationArticleViewRecentCnt]             INT            NULL,
    [myGroupsTastingNoteCnt]                        INT            NULL,
    [myGroupsTastingNoteRecentCnt]                  INT            NULL,
    [myGroupsTastingNoteRatedHelpfulCnt]            INT            NULL,
    [myGroupsTastingNoteRatedHelpfulRecentCnt]      INT            NULL,
    [myGroupsTastingNoteViewCnt]                    INT            NULL,
    [myGroupsTastingNoteViewRecentCnt]              INT            NULL,
    [myGroupsArticleCnt]                            INT            NULL,
    [myGroupsArticleRecentCnt]                      INT            NULL,
    [myGroupsArticleRatedHelpfulCnt]                INT            NULL,
    [myGroupsArticleRatedHelpfulRecentCnt]          INT            NULL,
    [myGroupsArticleViewCnt]                        INT            NULL,
    [myGroupsArticleViewRecentCnt]                  INT            NULL,
    [MyOwnTastingNoteCnt]                           INT            NULL,
    [MyOwnTastingNoteRecentCnt]                     INT            NULL,
    [MyOwnTastingNoteRatedHelpfulCnt]               INT            NULL,
    [MyOwnTastingNoteRatedHelpfulRecentCnt]         INT            NULL,
    [MyOwnTastingNoteViewCnt]                       INT            NULL,
    [MyOwnTastingNoteViewRecentCnt]                 INT            NULL,
    [MyOwnArticleCnt]                               INT            NULL,
    [MyOwnArticleRecentCnt]                         INT            NULL,
    [MyOwnArticleRatedHelpfulCnt]                   INT            NULL,
    [MyOwnArticleRatedHelpfulRecentCnt]             INT            NULL,
    [MyOwnArticleViewCnt]                           INT            NULL,
    [MyOwnArticleViewRecentCnt]                     INT            NULL,
    CONSTRAINT [PK_whEx] PRIMARY KEY CLUSTERED ([whN] ASC)
);

