CREATE TABLE [dbo].[whToWineX] (
    [whN]                   INT             NOT NULL,
    [wineN]                 INT             NOT NULL,
    [isOfInterestShow]      BIT             CONSTRAINT [DF_whToWineX_isOfInterest] DEFAULT (NULL) NULL,
    [wantToTryShow]         BIT             CONSTRAINT [DF_whToWineX_wantToTry] DEFAULT (NULL) NULL,
    [hasBottlesShow]        BIT             CONSTRAINT [DF_whToWineX_hasBottles] DEFAULT (NULL) NULL,
    [hasTastingsShow]       BIT             CONSTRAINT [DF_whToWineX_hasTastings] DEFAULT (NULL) NULL,
    [wantToBuyShow]         BIT             CONSTRAINT [DF_whToWineX_wantToBuy] DEFAULT (NULL) NULL,
    [wantToSellShow]        BIT             CONSTRAINT [DF_whToWineX_wantToSell] DEFAULT (NULL) NULL,
    [hasBuyersShow]         BIT             CONSTRAINT [DF_whToWineX_hasBuyers] DEFAULT (NULL) NULL,
    [hasSellersShow]        BIT             CONSTRAINT [DF_whToWineX_hasSellers] DEFAULT (NULL) NULL,
    [hasUserCommentsShow]   BIT             CONSTRAINT [DF_whToWineX_hasComments] DEFAULT (NULL) NULL,
    [isOfInterest]          BIT             CONSTRAINT [DF_whToWineX_isOfInterest1_1] DEFAULT (NULL) NULL,
    [wantToTry]             BIT             CONSTRAINT [DF_whToWineX_wantToTry1_1] DEFAULT (NULL) NULL,
    [bottleCount]           SMALLINT        CONSTRAINT [DF_whToWineX_bottleCount] DEFAULT (NULL) NULL,
    [hasMoreDetail]         BIT             CONSTRAINT [DF_whToWineX_hasBottleDetail] DEFAULT (NULL) NULL,
    [tastingCount]          SMALLINT        CONSTRAINT [DF_whToWineX_tastingCount] DEFAULT (NULL) NULL,
    [wantToSellBottleCount] SMALLINT        CONSTRAINT [DF_whToWineX_wantToSellCount] DEFAULT (NULL) NULL,
    [wantToBuyBottleCount]  SMALLINT        CONSTRAINT [DF_whToWineX_wantToBuyCount] DEFAULT (NULL) NULL,
    [buyerCount]            SMALLINT        CONSTRAINT [DF_whToWineX_buyerCount] DEFAULT (NULL) NULL,
    [sellerCount]           SMALLINT        CONSTRAINT [DF_whToWineX_sellerCount] DEFAULT (NULL) NULL,
    [userComments]          NVARCHAR (100)  CONSTRAINT [DF_whToWineX_userComments] DEFAULT (NULL) NULL,
    [isOfInterestR]         BIT             CONSTRAINT [DF_whToWineX_isOfInterest1] DEFAULT (NULL) NULL,
    [wantToTryR]            BIT             CONSTRAINT [DF_whToWineX_wantToTry1] DEFAULT (NULL) NULL,
    [hasBottlesR]           BIT             CONSTRAINT [DF_whToWineX_hasBottles1] DEFAULT (NULL) NULL,
    [hasTastingsR]          BIT             CONSTRAINT [DF_whToWineX_hasTastings1] DEFAULT (NULL) NULL,
    [wantToBuyR]            BIT             CONSTRAINT [DF_whToWineX_wantToBuy1] DEFAULT (NULL) NULL,
    [wantToSellR]           BIT             CONSTRAINT [DF_whToWineX_wantToSell1] DEFAULT (NULL) NULL,
    [hasBuyersR]            BIT             CONSTRAINT [DF_whToWineX_hasBuyers1] DEFAULT (NULL) NULL,
    [hasSellersR]           BIT             CONSTRAINT [DF_whToWineX_hasSellers1] DEFAULT (NULL) NULL,
    [hasUserCommentsR]      BIT             CONSTRAINT [DF_whToWineX_hasComments1] DEFAULT (NULL) NULL,
    [rowversion]            ROWVERSION      NULL,
    [locationN]             INT             CONSTRAINT [DF_whToWineX_locationN] DEFAULT (NULL) NULL,
    [hasHadStuff]           BIT             CONSTRAINT [DF_whToWineX_hasHadStuff] DEFAULT (NULL) NULL,
    [isDerived]             BIT             CONSTRAINT [df_mapwhToWineX_isDerived] DEFAULT (NULL) NULL,
    [warnings]              NVARCHAR (1000) NULL,
    [isOfInterestX]         BIT             CONSTRAINT [DF_whToWineX_isOfInterestShow1] DEFAULT (NULL) NULL,
    [wantToTryX]            BIT             CONSTRAINT [DF_whToWineX_wantToTryShow1] DEFAULT (NULL) NULL,
    [hasBottlesX]           BIT             CONSTRAINT [DF_whToWineX_hasBottlesShow1] DEFAULT (NULL) NULL,
    [hasTastingsX]          BIT             CONSTRAINT [DF_whToWineX_hasTastingsShow1] DEFAULT (NULL) NULL,
    [wantToBuyX]            BIT             CONSTRAINT [DF_whToWineX_wantToBuyShow1] DEFAULT (NULL) NULL,
    [wantToSellX]           BIT             CONSTRAINT [DF_whToWineX_wantToSellShow1] DEFAULT (NULL) NULL,
    [hasBuyersX]            BIT             CONSTRAINT [DF_whToWineX_hasBuyersShow1] DEFAULT (NULL) NULL,
    [hasSellersX]           BIT             CONSTRAINT [DF_whToWineX_hasSellersShow1] DEFAULT (NULL) NULL,
    [hasUserCommentsX]      BIT             CONSTRAINT [DF_whToWineX_hasUserCommentsShow1] DEFAULT (NULL) NULL,
    [isOfInterestIndirect]  BIT             NULL,
    [consumedCount]         SMALLINT        NULL,
    CONSTRAINT [PK_whToWineX] PRIMARY KEY CLUSTERED ([whN] ASC, [wineN] ASC)
);

