CREATE TABLE [dbo].[rpowinedataDWine] (
    [ArticleId]                 INT            NULL,
    [ArticleIdNKey]             INT            NULL,
    [clumpName]                 VARCHAR (50)   NULL,
    [ColorClass]                NVARCHAR (30)  NOT NULL,
    [Country]                   NVARCHAR (25)  NOT NULL,
    [DateUpdated]               SMALLDATETIME  NULL,
    [DrinkDate]                 DATE           NULL,
    [DrinkDate_Hi]              DATE           NULL,
    [Dryness]                   NVARCHAR (30)  NOT NULL,
    [encodedKeyWords]           NVARCHAR (255) NULL,
    [EntryN]                    INT            NOT NULL,
    [EstimatedCost]             MONEY          NULL,
    [FixedId]                   INT            NOT NULL,
    [HasCurrentPrice]           BIT            NULL,
    [hasErpTasting]             BIT            NULL,
    [hasProducerProfile]        BIT            NULL,
    [HasProducerWebSite]        BIT            NULL,
    [hasWJtasting]              BIT            NULL,
    [Idn]                       INT            NOT NULL,
    [IsActiveWineN]             SMALLINT       NOT NULL,
    [IsBarrelTasting]           BIT            NOT NULL,
    [IsCurrentlyForSale]        BIT            NULL,
    [isCurrentlyOnAuction]      BIT            NULL,
    [isErpTasting]              BIT            NULL,
    [Issue]                     NVARCHAR (255) NULL,
    [isWjTasting]               BIT            NULL,
    [LabelName]                 NVARCHAR (120) NOT NULL,
    [Locale]                    NVARCHAR (50)  NOT NULL,
    [Location]                  NVARCHAR (50)  NOT NULL,
    [Maturity]                  SMALLINT       NULL,
    [mostRecentAuctionPrice]    MONEY          NULL,
    [mostRecentAuctionPriceCnt] INT            NULL,
    [mostRecentAuctionPriceHi]  MONEY          NULL,
    [MostRecentPrice]           MONEY          NULL,
    [MostRecentPriceCnt]        INT            NULL,
    [MostRecentPriceHi]         MONEY          NULL,
    [Notes]                     NVARCHAR (MAX) NULL,
    [notesLen]                  BIGINT         NULL,
    [Places]                    NVARCHAR (150) NOT NULL,
    [Producer]                  NVARCHAR (100) NOT NULL,
    [ProducerProfileFileName]   VARCHAR (50)   NULL,
    [ProducerShow]              NVARCHAR (100) NOT NULL,
    [ProducerURL]               NVARCHAR (255) NULL,
    [Publication]               NVARCHAR (50)  NULL,
    [Rating]                    SMALLINT       NULL,
    [Rating_Hi]                 SMALLINT       NULL,
    [RatingQ]                   VARCHAR (2)    NULL,
    [RatingShow]                VARCHAR (45)   NULL,
    [Region]                    NVARCHAR (50)  NOT NULL,
    [ReviewerIdN]               INT            NULL,
    [ShortLabelName]            NVARCHAR (120) NOT NULL,
    [ShortTitle]                INT            NULL,
    [showForERP]                BIT            NULL,
    [showForWJ]                 BIT            NULL,
    [Site]                      NVARCHAR (25)  NOT NULL,
    [SomeYearHasPrices]         BIT            NULL,
    [Source]                    NVARCHAR (101) NOT NULL,
    [SourceDate]                DATE           NULL,
    [tasteDate]                 DATE           NULL,
    [ThisYearHasPrices]         BIT            NULL,
    [Variety]                   NVARCHAR (50)  NOT NULL,
    [VinN]                      INT            NULL,
    [Vintage]                   NVARCHAR (4)   NOT NULL,
    [WineN]                     INT            NULL,
    [WineType]                  NVARCHAR (50)  NOT NULL
);

