CREATE VIEW [dbo].[vWine4Erp]

AS

select --top 20
	--articleHandle,
	ArticleId = w.ArticleID,
	ArticleIdNKey = w.ArticleIdNKey,
	--articleMasterN,ArticleOrder,
	BottleSize,
	--BottlesPerCosting,canBeActiveTasting,
	clumpName,ColorClass,
	--CombinedLocation,
	Country,
	DateUpdated = tn.updated,	-- ????
	DrinkDate = w.DrinkDate,
	DrinkDate_Hi = w.DrinkDate_hi,
	Dryness,encodedKeyWords,
	EntryN = w.TasteNote_ID,
	--erpTastingCount,
	EstimatedCost = w.EstimatedCost,
	--EstimatedCost_Hi,
	FixedId = w.FixedId,
	--hasAGalloniTasting,
	HasCurrentPrice = cast(case when wn.MostRecentPrice is not null then 1 else 0 end as bit),
	--hasDSchildknechtTasting,hasDThomasesTasting,
	hasErpTasting = wn.hasERPTasting,
	--hasJMillerTasting,
	--hasMSquiresTasting,hasMultipleWATastings,hasNMartinTasting,
	hasProducerProfile = cast(case when w.ProducerProfileFileName is NULL then 0 else 1 end as bit),
	HasProducerWebSite = cast(case when w.ProducerURL is NULL then 0 else 1 end as bit),
	--hasPRovaniTasting,hasRParkerTasting,
	hasWJtasting = wn.hasWJTasting,
	Idn = w.IdN,
	--isActiveT,IsActiveTasting,
	IsActiveWineN = w.IsActiveWineN,
	--isActiveWineN_old,isActiveWineN2,isActiveWineNRpwacm,
	IsBarrelTasting = tn.IsBarrelTasting,
	--isBorrowedDrinkDate,
	IsCurrentlyForSale = w.IsCurrentlyForSale,
	isCurrentlyOnAuction = w.IsCurrentlyOnAuction,
	--IsERPName,
	isErpTasting,
	--isMostRecentTasting,isNoTasting,
	Issue,isWjTasting,
	--joinA,joinX,
	LabelName,Locale,Location,Maturity,
	mostRecentAuctionPrice = wn.MostRecentAuctionPrice,
	mostRecentAuctionPriceCnt = wn.MostRecentAuctionPriceCnt,
	mostRecentAuctionPriceHi = wn.MostRecentAuctionPriceHi,
	MostRecentPrice = wn.MostRecentPrice,
	MostRecentPriceCnt = wn.MostRecentPriceCnt,
	MostRecentPriceHi = wn.MostRecentPriceHi,
	Notes = w.Notes,
	notesLen = datalength(w.Notes),
	--originalEstimatedCost,originalEstimatedCost_hi,Pages,
	Places,
	Producer,
	ProducerProfileFileName,
	ProducerShow,
	ProducerURL,
	Publication,
	Rating = nullif(Rating, 0),
	Rating_Hi = nullif(tn.Rating_Hi, 0),
	RatingQ = tn.RatingQ,
	RatingShow,
	Region,ReviewerIdN,
	ShortLabelName = w.LabelName,
	ShortTitle,
	showForERP,
	showForWJ,
	Site,
	SomeYearHasPrices = cast(case when wn.MostRecentPrice is NULL then 0 else 1 end as bit),
	Source,SourceDate,
	tasteDate = tn.TasteDate,
	--TastingCount,temp,
	ThisYearHasPrices = cast(case when wn.MostRecentPrice is NULL then 0 else 1 end as bit),	-- WRONG!
	Variety,
	--Vin,
	VinN = isnull(w.oldVinN, 250000 + w.VinN),
	Vintage,
	--WhoUpdated,
	WineN = isnull(w.oldWineN, 250000 + w.WineN),
	--WineNameIdN,wineNameN,
	WineType
from Wine w (nolock)
	join Wine_N wn (nolock) on w.Wine_N_ID = wn.ID
	join TasteNote tn (nolock) on w.TasteNote_ID = tn.ID
--where w.fixedId is NOT NULL	--- used TasteNote.ID